name = "StochasticWeatherGenerator"
uuid = "3eadb0b9-5057-49d2-9b8f-52a8c334ebf6"
authors = ["David Métivier <46794064+dmetivie@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
